---
title: "percentage_comparison"
author: "Xinghao Gu"
date: "August 27, 2018"
output: html_document
---


```{r}
sim_prop <- function(N, trial1, trial2 = trial1, 
                     theta1, theta2 = theta2) {
  success1 <- rbinom(N, trial1, theta1)
  success2 <- rbinom(N, trial2, theta2)
  output_tab <- data.frame(success1 = success1,
                           success2 = success2,
                           total1 = trial1,
                           total2 = trial2) %>%
    rowwise() %>% 
    mutate(p1 = success1/total1,
           p2 = success2/total2,
           se1 = sqrt(p1*(1-p1)/(total1-1)),
           se2 = sqrt(p2*(1-p2)/(total2-1)),
           t_stat = (abs(p1 - p2)/sqrt(se1^2 + se2^2)),
           t_p = 2 * (1 - pt(t_stat, total1+total2-2)),
           chi_p = prop.test(c(success1, success2), 
                             c(total1, total2),
                             correct = F)$p.value) %>% 
    ungroup() %>% 
    summarise(`T-test Reject Percentage` = mean(t_p < 0.05),
              `Chi-squared Reject Percentage` = mean(chi_p < 0.05))
  
  output_tab
}
```

```{r, warning=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
# simulate for (0.5, 0.5)
data.frame(group1 = c(10, 15, 20, 40, 100),
           group2 = c(30, 15, 20, 40, 100)) %>%
  rowwise() %>% 
  do(
    data.frame(`Group 1 Size` = .$group1, `Group 2 Size` = .$group2,
              sim_prop(1000, .$group1, .$group2, 0.5, 0.5), 
              check.names = F) %>% 
      bind_rows() 
      
  ) %>% 
  kable(caption = "Simulation on True Percentage is 0.5 and 0.5") %>% 
  kable_styling(full_width = F, position = "c", 
                bootstrap_options = c("striped", "hover"),
                font_size = 15)
```


```{r, warning=FALSE, message=FALSE}
# simulate for (0.4, 0.6)
data.frame(group1 = c(10, 15, 20, 40, 100),
           group2 = c(30, 15, 20, 40, 100)) %>%
  rowwise() %>% 
  do(
    data.frame(`Group 1 Size` = .$group1, `Group 2 Size` = .$group2,
              sim_prop(1000, .$group1, .$group2, 0.4, 0.6), 
              check.names = F) %>% 
      bind_rows() 
      
  ) %>% 
  kable(caption = "Simulation on True Percentage is 0.4 and 0.6") %>% 
  kable_styling(full_width = F, position = "c", 
                bootstrap_options = c("striped", "hover"),
                font_size = 15)
```


```{r, warning=FALSE, message=FALSE}
# simulate for (0.3, 0.7)
data.frame(group1 = c(10, 15, 20, 40, 100),
           group2 = c(30, 15, 20, 40, 100)) %>%
  rowwise() %>% 
  do(
    data.frame(`Group 1 Size` = .$group1, `Group 2 Size` = .$group2,
              sim_prop(1000, .$group1, .$group2, 0.3, 0.7), 
              check.names = F) %>% 
      bind_rows() 
      
  ) %>% 
  kable(caption = "Simulation on True Percentage is 0.3 and 0.7") %>% 
  kable_styling(full_width = F, position = "c", 
                bootstrap_options = c("striped", "hover"),
                font_size = 15)
```
