---
title: "percentage_comparison"
author: "Xinghao"
date: "August 27, 2018"
output: html_document
---

If we try to compare two percentage from two uncorrelated populations, which test should we use, t-test or chi-squared test?

Here is the example, suppose we want to test whether the prevalence of overweight is different between men and women. Suppose we did an investigation and got the estimated overweight prevalence in both men and women population, then what's next? 

Student's t-test is a very popular method to compare population means, while in most cases it only works for numeric data because of one of the assumptions of Students' t-test: The mean follows a normal distribution. In our case, however, we have a binary output for each sample (overweight or not). A more typical method for this situation is Chi-squared test. 

Therefore, if we still want to use Students' t-test to test where there's a significant difference between the two overweight prevalences, is it correct? Why or why not?

We know the percentage of being overweight is a Bernoulli distribution with parameter P. And the number of people who are overweight is a binomial distribution with parameter P and N, where N is the sample size of that group. It has been proved (CLT) that binomial distribution is asymptotic to a normal distribution when NP and N(1-P) are both greater than 5. Thus, the percentage of being overweight is asymptotic to a normal distribution with mean = P and variance = P(1-P)/N.

Next, we did a simulation to compare the test result between using Chi-squared test and Student's t-test.

```{r}
sim_prop <- function(N, trial1, trial2 = trial1, 
                     theta1, theta2 = theta2) {
  success1 <- rbinom(N, trial1, theta1)
  success2 <- rbinom(N, trial2, theta2)
  data.frame(success1 = success1,
             success2 = success2,
             total1 = trial1,
             total2 = trial2) %>%
    rowwise() %>% 
    mutate(p1 = success1/total1,
           p2 = success2/total2,
           se1 = sqrt(p1*(1-p1)/(total1-1)),
           se2 = sqrt(p2*(1-p2)/(total2-1)),
           t_stat = (abs(p1 - p2)/sqrt(se1^2 + se2^2)),
           t_p = 2 * (1 - pt(t_stat, total1+total2-2)),
           chi_p = prop.test(c(success1, success2), c(total1, total2))$p.value) %>% 
    ungroup() %>% 
    summarise(t_reject = mean(t_p < 0.05),
              chi_reject = mean(chi_p < 0.05))
}
```



